// src/main/java/com/example/receipt_backend/mapper/ReceiptTypeMapper.java
package com.example.receipt_backend.mapper;

import com.example.receipt_backend.dto.ReceiptFieldDTO;
import com.example.receipt_backend.dto.request.ReceiptTypeRequestDTO;
import com.example.receipt_backend.dto.request.ReceiptTypeUpdateRequestDTO;
import com.example.receipt_backend.dto.response.ReceiptTypeResponseDTO;
import com.example.receipt_backend.entity.ReceiptField;
import com.example.receipt_backend.entity.ReceiptType;
import org.mapstruct.*;

import java.util.List;

@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface ReceiptTypeMapper {

    // Mapping from Request DTO to Entity
    @Mapping(target = "receiptTypeId", ignore = true) // ID is generated by the database
    ReceiptType toEntity(ReceiptTypeRequestDTO dto);

    ReceiptTypeResponseDTO toResponseDTO(ReceiptType receiptType);

    List<ReceiptTypeResponseDTO> toResponseDTOList(List<ReceiptType> entities);

    ReceiptField toEntity(ReceiptFieldDTO dto);
    ReceiptFieldDTO toDto(ReceiptField entity);

    List<ReceiptField> toEntityList(List<ReceiptFieldDTO> dtos);
    List<ReceiptFieldDTO> toDtoList(List<ReceiptField> entities);

    @BeanMapping(nullValuePropertyMappingStrategy =  NullValuePropertyMappingStrategy.IGNORE)
    void updateEntity(ReceiptTypeUpdateRequestDTO dto, @MappingTarget ReceiptType entity);}
