name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven Packages (if using Maven)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn clean verify

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 6: Build and Push Docker Image with Jib (Commit SHA Tag)
      - name: Build and Push Docker image with Jib (Commit SHA)
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          mvn compile jib:build -Dimage=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}

      # Step 7: Build and Push Docker Image with Jib (latest Tag)
      - name: Build and Push Docker image with Jib (latest)
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          mvn compile jib:build -Dimage=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest

      # Step 8: Deploy to Koyeb
      - name: Deploy to Koyeb
        env:
          KOYEB_API_KEY: ${{ secrets.KOYEB_API_KEY }}
          KOYEB_APP_NAME: ${{ secrets.KOYEB_APP_NAME }}
          IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
          KOYEB_REGION: ${{ secrets.KOYEB_REGION }}
        run: |
          curl -X PUT "https://api.koyeb.com/v1/services/${{ secrets.KOYEB_APP_NAME }}" \
          -H "Authorization: Bearer $KOYEB_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
                "image": "'"${IMAGE_NAME}"'",
                "region": "'"${KOYEB_REGION}"'"
              }'
