name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Build and Push Docker image with Jib
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          MAVEN_OPTS: "-Ddocker.username=${{ secrets.DOCKER_HUB_USERNAME }} -Ddocker.password=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
        run: mvn jib:build -Dimage=${{ secrets.DOCKER_HUB_USERNAME }}/{{ secrets.IMAGE_NAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Koyeb
        env:
          KOYEB_API_KEY: ${{ secrets.KOYEB_API_KEY }}
        run: |
          curl -X POST https://api.koyeb.com/v1/services \
            -H "Authorization: Bearer $KOYEB_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "my-spring-boot-app",
              "service_type": "web",
              "region": "us-east-1",
              "image": "${{ secrets.DOCKER_HUB_USERNAME }}/{{ secrets.IMAGE_NAME }}:latest",
              "envs": [
                {
                  "key": "SPRING_DATASOURCE_URL",
                  "value": "${{ secrets.SPRING_DATASOURCE_URL }}"
                },
                {
                  "key": "SPRING_DATASOURCE_USERNAME",
                  "value": "${{ secrets.SPRING_DATASOURCE_USERNAME }}"
                },
                {
                  "key": "SPRING_DATASOURCE_PASSWORD",
                  "value": "${{ secrets.SPRING_DATASOURCE_PASSWORD }}"
                },
                {
                  "key": "MAIL_HOST",
                  "value": "${{ secrets.MAIL_HOST }}"
                },
                {
                  "key": "MAIL_USERNAME",
                  "value": "${{ secrets.MAIL_USERNAME }}"
                },
                {
                  "key": "MAIL_PASSWORD",
                  "value": "${{ secrets.MAIL_PASSWORD }}"
                },
                {
                  "key": "MAIL_PORT",
                  "value": "${{ secrets.MAIL_PORT }}"
                },
                {
                  "key": "GOOGLE_CLIENT_ID",
                  "value": "${{ secrets.GOOGLE_CLIENT_ID }}"
                },
                {
                  "key": "GOOGLE_CLIENT_SECRET",
                  "value": "${{ secrets.GOOGLE_CLIENT_SECRET }}"
                },
                {
                  "key": "GOOGLE_REDIRECT_URI",
                  "value": "${{ secrets.GOOGLE_REDIRECT_URI }}"
                },
                {
                  "key": "AWS_ACCESS_KEY",
                  "value": "${{ secrets.AWS_ACCESS_KEY }}"
                },
                {
                  "key": "AWS_SECRET_KEY",
                  "value": "${{ secrets.AWS_SECRET_KEY }}"
                },
                {
                  "key": "AWS_S3_BUCKET",
                  "value": "${{ secrets.AWS_S3_BUCKET }}"
                },
                {
                  "key": "AWS_REGION",
                  "value": "${{ secrets.AWS_REGION }}"
                },
                {
                  "key": "JWT_SECRET",
                  "value": "${{ secrets.JWT_SECRET }}"
                }
              ],
              "resources": {
                "cpu": "500m",
                "memory": "512Mi",
                "storage": "1Gi"
              },
              "scale": {
                "min": 1,
                "max": 2
              }
            }'
