name: CI/CD Pipeline

on: [push, pull_request]

env:
  MAVEN_ARGS: >-
    -V -B 
    --no-transfer-progress 
    -Dhttp.keepAlive=false 
    -Dmaven.wagon.http.pool=false 
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java: [21]
        os: [ubuntu-latest]
    name: 'Test on ${{ matrix.os }} with JDK ${{ matrix.java }}'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Run tests
        run: ./mvnw ${MAVEN_ARGS} clean verify

  build-and-publish:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push with Jib
        run: |
          ./mvnw ${MAVEN_ARGS} clean compile jib:build \
            -Djib.to.auth.username=${{ secrets.DOCKER_HUB_USERNAME }} \
            -Djib.to.auth.password=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to Koyeb
        env:
          KOYEB_API_KEY: ${{ secrets.KOYEB_API_KEY }}
        run: |
          curl -X POST https://api.koyeb.com/v1/services \
            -H "Authorization: Bearer $KOYEB_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "my-spring-boot-app",
              "service_type": "web",
              "region": "us-east-1",
              "image": "${{ secrets.DOCKER_HUB_USERNAME }}/{{ secrets.IMAGE_NAME }}:latest",
              "envs": [
                {
                  "key": "SPRING_DATASOURCE_URL",
                  "value": "${{ secrets.SPRING_DATASOURCE_URL }}"
                },
                {
                  "key": "SPRING_DATASOURCE_USERNAME",
                  "value": "${{ secrets.SPRING_DATASOURCE_USERNAME }}"
                },
                {
                  "key": "SPRING_DATASOURCE_PASSWORD",
                  "value": "${{ secrets.SPRING_DATASOURCE_PASSWORD }}"
                }
              ],
              "resources": {
                "cpu": "500m",
                "memory": "512Mi",
                "storage": "1Gi"
              },
              "scale": {
                "min": 1,
                "max": 2
              }
            }'
